language: cpp

compiler:
  - gcc
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - sudo apt-get update && sudo apt-get install -y fglrx opencl-headers libboost-thread-dev libboost-system-dev libboost-iostreams-dev  libboost-filesystem-dev libboost-date-time-dev libopencv-dev

script:
  - cmake -G "Unix Makefiles" .
  - make
  - ./bin/test_gcvl

branches:
  only:
    - master

notifications:
  email: false

os:
  - linux
  - osx
