language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository --yes ppa:boost-latest/ppa
  - sudo apt-get update && sudo apt-get install -y fglrx opencl-headers libboost1.55-dev libopencv-dev
  - sudo ln /dev/null /dev/raw1394


script:
  - cmake -G "Unix Makefiles" .
  - make
  - ./bin/test_gcvl data/tsukuba_l.png data/tsukuba_r.png

branches:
  only:
    - master

notifications:
  email: false

os:
  - linux
  - osx
