language: cpp

compiler:
  - gcc
  - clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository --yes ppa:boost-latest/ppa; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update && sudo apt-get install -y fglrx opencl-headers boost1.55 libopencv-dev lcov;
    else
      brew update && brew tap homebrew/science && brew install opencv;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ln /dev/null /dev/raw1394; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then gem install coveralls-lcov; fi

script:
  - cmake -G "Unix Makefiles" -DBUILD_OPENCL=ON -DBUILD_CUDA=OFF -DBUILD_TESTS=ON .
  - make
  - ./bin/test_cpu data/tsukuba_l.png data/tsukuba_r.png
  - ./bin/test_opencl data/tsukuba_l.png data/tsukuba_r.png

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info # filter out system and test
  - lcov --list coverage.info # debug before upload
  - coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info # uploads to coveralls

branches:
  only:
    - master

notifications:
  email: false

os:
  - linux
  - osx
