language: cpp
compiler:
  - gcc
  - clang
before_install:
  - openssl aes-256-cbc -K $encrypted_4e78e1c3dc1b_key -iv $encrypted_4e78e1c3dc1b_iv -in tools/travisci_rsa.enc -out tools/travisci_rsa -d
  - chmod 0600 tools/travisci_rsa
  - cp tools/travisci_rsa ~/.ssh/id_rsa
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository --yes ppa:boost-latest/ppa; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update && sudo apt-get install -y fglrx opencl-headers boost1.55 libopencv-dev lcov doxygen;
    else
      brew update && brew tap homebrew/science && brew install opencv;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ln /dev/null /dev/raw1394; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then gem install coveralls-lcov; fi
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DCOVERALLS=ON -DBUILD_OPENCL=ON -DBUILD_CUDA=OFF -DBUILD_TESTS=ON .;
    else
      cmake -G "Unix Makefiles" -DBUILD_OPENCL=ON -DBUILD_CUDA=OFF -DBUILD_TESTS=ON .;
    fi
  - make
  - "./bin/test_cpu data/tsukuba_l.png data/tsukuba_r.png"
  - "./bin/test_opencl data/tsukuba_l.png data/tsukuba_r.png"
after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CXX" == "g++" ]]; then lcov --directory . --capture --output-file coverage.info; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CXX" == "g++" ]]; then lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CXX" == "g++" ]]; then lcov --list coverage.info; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CXX" == "g++" ]]; then coveralls-lcov coverage.info; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CXX" == "g++" ]]; then ./tools/push-doxygen.sh; fi
branches:
  only:
    - master
notifications:
  email: false
os:
  - linux
  - osx
