language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update && sudo apt-get install -y fglrx opencl-headers libboost-thread-dev libboost-system-dev libboost-iostreams-dev  libboost-filesystem-dev libboost-date-time-dev libopencv-dev
  #- sudo apt-get install libc++1 multiarch-support libc6 libc++-dev
  - if [ "$CXX" == "clang++" ]; then svn co --quiet http://llvm.org/svn/llvm-project/libcxx/trunk libcxx; fi
  - if [ "$CXX" == "clang++" ]; then cd libcxx/lib && bash buildit; fi
  - if [ "$CXX" == "clang++" ]; then sudo cp ./libc++.so.1.0 /usr/lib/; fi
  - if [ "$CXX" == "clang++" ]; then sudo mkdir /usr/include/c++/v1; fi
  - if [ "$CXX" == "clang++" ]; then cd .. && sudo cp -r include/* /usr/include/c++/v1/; fi
  - if [ "$CXX" == "clang++" ]; then cd /usr/lib && sudo ln -sf libc++.so.1.0 libc++.so; fi
  - if [ "$CXX" == "clang++" ]; then sudo ln -sf libc++.so.1.0 libc++.so.1 && cd $cwd; fi
  - popd
  - sudo ln /dev/null /dev/raw1394

script:
  - cmake -G "Unix Makefiles" .
  - make
  - ./bin/test_gcvl data/tsukuba_l.png data/tsukuba_r.png

branches:
  only:
    - master

notifications:
  email: false

os:
  - linux
  - osx
