language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update && sudo apt-get install -y fglrx opencl-headers libboost-thread-dev libboost-system-dev libboost-iostreams-dev  libboost-filesystem-dev libboost-date-time-dev  build-essential #libopencv-dev
  - curl -sL https://github.com/Itseez/opencv/archive/2.4.11.zip > opencv.zip
  - unzip opencv.zip
  - rm opencv.zip
  - mkdir opencv-build
  - cd opencv-build/
  - cmake ../opencv-2.4.11/
  - sudo make install
  - cd ..
  - sudo ln /dev/null /dev/raw1394

script:
  - cmake -G "Unix Makefiles" .
  - make
  - ./bin/test_gcvl

branches:
  only:
    - master

notifications:
  email: false

os:
  - linux
  - osx
