language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository --yes ppa:boost-latest/ppa
  - sudo apt-get update && sudo apt-get install -y fglrx opencl-headers boost1.55 libopencv-dev
  - sudo ln /dev/null /dev/raw1394


script:
  - cmake -G "Unix Makefiles" -DBUILD_OPENCL=ON -DBUILD_CUDA=OFF -DBUILD_TESTS=ON .
  - make
  - ./bin/test_cpu data/tsukuba_l.png data/tsukuba_r.png
  - ./bin/test_opencl data/tsukuba_l.png data/tsukuba_r.png

branches:
  only:
    - master

notifications:
  email: false

os:
  - linux
  - osx
