language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update && sudo apt-get install -y fglrx opencl-headers libboost-thread-dev libboost-system-dev libboost-iostreams-dev  libboost-filesystem-dev libboost-date-time-dev  build-essential libopencv-dev
  - sudo /bin/bash -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf'
  - sudo ldconfig
  - sudo ln /dev/null /dev/raw1394

script:
  - cmake -G "Unix Makefiles" .
  - make
  - ./bin/test_gcvl

branches:
  only:
    - master

notifications:
  email: false

os:
  - linux
  - osx
