var files =
[
    [ "src/gcvl/algorithm.cpp", "algorithm_8cpp.html", null ],
    [ "src/gcvl/algorithm.h", "algorithm_8h.html", null ],
    [ "src/gcvl/blockmatching.cpp", "blockmatching_8cpp.html", null ],
    [ "src/gcvl/blockmatching.h", "blockmatching_8h.html", null ],
    [ "src/gcvl/export.h", "export_8h.html", "export_8h" ],
    [ "src/gcvl/gcvlconfig.h", "gcvlconfig_8h.html", null ],
    [ "src/gcvl/gcvlutils.h", "gcvlutils_8h.html", "gcvlutils_8h" ],
    [ "src/gcvl/cuda/cudaalgorithm.cpp", "cudaalgorithm_8cpp.html", null ],
    [ "src/gcvl/cuda/cudaalgorithm.h", "cudaalgorithm_8h.html", null ],
    [ "src/gcvl/cuda/cudablockmatching.cpp", "cudablockmatching_8cpp.html", null ],
    [ "src/gcvl/cuda/cudablockmatching.h", "cudablockmatching_8h.html", null ],
    [ "src/gcvl/cuda/cudacore.cpp", "cudacore_8cpp.html", null ],
    [ "src/gcvl/cuda/cudacore.h", "cudacore_8h.html", null ],
    [ "src/gcvl/cuda/cudautils.cpp", "cudautils_8cpp.html", null ],
    [ "src/gcvl/cuda/cudautils.h", "cudautils_8h.html", "cudautils_8h" ],
    [ "src/gcvl/opencl/oclalgorithm.cpp", "oclalgorithm_8cpp.html", null ],
    [ "src/gcvl/opencl/oclalgorithm.h", "oclalgorithm_8h.html", null ],
    [ "src/gcvl/opencl/oclblockmatching.cpp", "oclblockmatching_8cpp.html", "oclblockmatching_8cpp" ],
    [ "src/gcvl/opencl/oclblockmatching.h", "oclblockmatching_8h.html", null ],
    [ "src/gcvl/opencl/oclcore.cpp", "oclcore_8cpp.html", null ],
    [ "src/gcvl/opencl/oclcore.h", "oclcore_8h.html", null ],
    [ "src/gcvl/opencl/oclutils.cpp", "oclutils_8cpp.html", "oclutils_8cpp" ],
    [ "src/gcvl/opencl/oclutils.h", "oclutils_8h.html", "oclutils_8h" ],
    [ "src/test_cpu/test_cpu.cpp", "test__cpu_8cpp.html", "test__cpu_8cpp" ],
    [ "src/test_cuda/test_cuda.cpp", "test__cuda_8cpp.html", "test__cuda_8cpp" ],
    [ "src/test_opencl/test_opencl.cpp", "test__opencl_8cpp.html", "test__opencl_8cpp" ]
];